# Generated by Django 3.2.16 on 2022-11-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_item_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_modified']},
        ),
    ]
